repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^releases/
  - repo: local
    hooks:
      - id: pytest-quick
        name: pytest-quick
        entry: bash -lc 'pytest -q'
        language: system
        pass_filenames: false
        stages: [pre-push]
