coverage:
  status:
    project:
      default:
        target: 96%
        threshold: 0.2%
        informational: false
    patch:
      default:
        target: 0%
        threshold: 1%
        informational: true
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
