name: bmi-app-test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyter
  - ipykernel
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pip:
      - fastapi
      - uvicorn
      - huggingface_hub
