name: CI
permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Security scan with Bandit (non-blocking)
        run: bandit -r . -x tests,tests_strict,htmlcov -f json -o bandit-report.json || true

      # Safety scan disabled due to typer compatibility issue
      # See: https://github.com/pyupio/safety/issues/566
      # - name: Security scan with Safety (non-blocking)
      #   run: safety scan --output json > safety-report.json || true

      - name: Run tests with coverage (97% required)
        env:
          PYTHONPATH: .
          APP_ENV: ci
        run: |
          pytest -q --maxfail=1 --cov=. --cov-report=term-missing --cov-report=xml --cov-fail-under=96

      - name: Upload coverage.xml
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml

      - name: Upload coverage to Codecov (non-blocking)
        if: ${{ always() }}
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4
        with:
          file: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: true
