name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Security scan with Bandit (non-blocking)
      run: |
        # Exclude tests and coverage artifacts to avoid false positives (e.g., B101 asserts)
        # Make non-blocking for CI stability; review bandit-report.json in artifacts if needed.
        bandit -r . -x tests,tests_strict,htmlcov -f json -o bandit-report.json || true
    - name: Security scan with Safety (non-blocking)
      run: |
        safety check --output json > safety-report.json || true
    - name: Run tests
      run: |
        pytest --cov=app --cov=bmi_core --cov=bodyfat --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
