name: Deploy to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Hugging Face
        run: |
          pip install --upgrade pip huggingface_hub
          python -c "from huggingface_hub import HfApi; import os; api=HfApi(); api.whoami(token=os.environ['HF_TOKEN'])"

        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

      - name: Push repo to Space (mirror main)
        run: |
          git remote add space https://huggingface.co/spaces/LEXAKM532/Bmi2025 || true
          git push space HEAD:main --force
