name: python-tests
permissions:
  contents: read
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt

      - name: Run tests (96% coverage required)
        env:
          PYTHONPATH: .
          APP_ENV: ci
        run: pytest -q --maxfail=1 --cov=. --cov-report=term-missing --cov-report=xml --cov-fail-under=96

      - name: Run strict tests with RU strict localization
        env:
          PYTHONPATH: .
          APP_ENV: ci
          RU_STRICT_LOCALIZATION: "1"
        run: pytest -q --maxfail=1 --cov=. --cov-report=term-missing --cov-report=xml:coverage-strict.xml --cov-fail-under=95 tests_strict

      - name: Upload coverage-strict.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-strict-${{ matrix.python-version }}
          path: coverage-strict.xml

      - name: Upload strict coverage to Codecov (non-blocking)
        if: ${{ always() }}
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4
        with:
          file: ./coverage-strict.xml
          token: ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: true

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml

      - name: Upload coverage to Codecov (non-blocking)
        if: ${{ always() }}
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4
        with:
          file: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: true
