name: Test headers check
on:
  push:
  pull_request:

jobs:
  check-headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure test header present
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          files=(tests/*.py tests_strict/*.py)
          missing=()
          for f in "${files[@]}"; do
            if ! grep -qE "sys\.path\.insert\(0,\s*str\(pathlib\.Path\(__file__\)\.resolve\(\)\.parent\.parent\)\)" "$f"; then
              missing+=("$f")
            fi
          done
          if ((${#missing[@]})); then
            echo "::error::Missing import header in the following files:"
            printf "%s\n" "${missing[@]}"
            exit 1
          fi
          echo "OK: all test files have the required header."
